---
# See https://pre-commit.com for more information
default_language_version:
  python: python3.11

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-yaml
      - id: check-added-large-files
        args:
          - '--maxkb=1024'
      - id: debug-statements
      - id: mixed-line-ending
        args:
          - '--fix=lf'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        alias: autoformat
        args:
          - '--fix'
          - '--exit-non-zero-on-fix'

  - repo: 'https://github.com/psf/black'
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/pdm-project/pdm
    rev: 2.8.2
    hooks:
      - id: pdm-lock-check
