site_name: Chrophos Documentation
site_url: https://example.com/chrophos
nav:
  - Home: index.md
  - Examples: examples.md
  - Overview: overview.md

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
