camera_model = "Canon EOS 5D Mark II"
shutter_min = "1/8000"
shutter_max = "30"
aperture_min = 2
# As per https://www.dxomark.com/Lenses/Canon/Canon-EF-100mm-F2-USM-mounted-on-Canon-EOS-5D-Mark-II---Measurements__483
aperture_max = 11
iso_min = 100
iso_max = 6400  # As per https://www.photonstophotos.net/Charts/PDR_Shadow.htm
mode = "aperture_priority"
dark_time = 5

[config_map]
shutter = "shutterspeed"
aperture = "aperture"
iso = "iso"

[config_map.shutter_release]
key = "eosremoterelease"
values.full_press = "Press Full"
values.half_press = "Press Half"
values.half_release = "Release Half"

[config_map.auto_exposure_mode]
key = "autoexposuremode"
values.manual = "Manual"
values.aperture_priority = "AV"
values.shutter_priority = "TV"
values.program = "P"
