camera_model = "Nikon Z6"

[dark_time]
2 = 2
30 = 6

[parameters]

[parameters.shutter]
type = "discrete"
valid_max = 1
target = 1
config_key = "shutterspeed2"

[parameters.aperture]
type = "discrete"
target = "f/8"
valid_max = "f/16"
config_key = "f-number"

[parameters.iso]
type = "discrete"
valid_min = 100 # Don't go below base ISO
valid_max = 800 # Don't go above second "base ISO" (https://www.photonstophotos.net/Charts/PDR.htm#Nikon%20Z%206)
target = 100 # Stay as low as possible
config_key = "iso"

[parameters.silent_capture]
type = "boolean"
config_key = "d1ad"
true = "1" # True is represented as 1 in gphoto2
false = "0" # False is represented by 0 in gphoto2
initial_value = "1"

[parameters.light_meter]
type = "range"
read_only = true
config_key = "lightmeter"

[parameters.image_type]
type = "discrete"
initial_value = "NEF (Raw)"
config_key = "imagequality"

[parameters.mode]
type = "discrete"
read_only = true
valid_choices = ["U1"]
config_key = "expprogram"

[parameters.ev_step_size]
type = "discrete"
config_key = "evstep"
initial_value = "1/3"

[parameters.datetime]
type = "datetime"
config_key = "datetime"
